### ISSUE TITLE
Generalise the use of the app

### ISSUE THREAD

**Issue by GrimPixel** [specht/hamfisted#1]
It can be used not only for Hamradio training, but also for any training. 
Then custom files would be used. It would be better to use a markup language like AsciiDoc or Markdown to store quizzes.

**Comment by specht** [comment]
Thanks for the suggestion. Feel free to use it for whatever kind of training. The input files are in XML format because that's what I got from somewhere. They just get converted to JSON though via `parse.rb`, so any kind of input file would do with a matching preprocessing parser.

**Comment by GrimPixel** [comment]
Thanks for the explanation. I see the data directory. I would do it in another way: a subdirectory for the media, divide the questions into multiple files. 

What about having the feature that users can import their own data folder to the app?

**Comment by specht** [comment]
The input format isn't that important – if you have questions with answers that are arranged in a hierarchical structure (and if you have 4 answers for every question of which exactly 1 is correct), this app is going to handle it. In the end, all data ends up in `questions.js` and it would be pretty simple to write a script that turns a directory structure with one question per file into JSON, just like the script I wrote that turns the decades-old XML file into JSON. Do you have a specific use case in mind?

I think it's out of scope of _this_ app to let users import their own questions (which introduces more complexity and potentially problems on the user's side), but no one's stopping you from taking the source code and changing it to suit your needs, so go ahead and play around with the source code. Do you have Flutter installed?

**Comment by GrimPixel** [comment]
OK, then it is settled. Another app can do so. Building from source is incovenient for customisation.
